@CleanArchitecture.Presentation.API_HostAddress = http://localhost:5156

GET {{CleanArchitecture.Presentation.API_HostAddress}}/api/radio/
Accept: application/json

###
GET {{CleanArchitecture.Presentation.API_HostAddress}}/api/seeder/
Accept: application/json