@CleanArchitecture.Presentation.API_HostAddress = https://localhost:5000

GET {{CleanArchitecture.Presentation.API_HostAddress}}/api/BloodPressures
Accept: application/json

###
POST {{CleanArchitecture.Presentation.API_HostAddress}}/api/BloodPressures
Content-Type: application/json

{
  
}